# Generated by Django 4.2 on 2024-11-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0002_videocurses'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocurses',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
